---
timestamp: 'Tue Oct 14 2025 22:58:32 GMT-0400 (Eastern Daylight Time)'
parent: '[[../20251014_225832.3eff4204.md]]'
content_id: 3db0fc0ea7b41c5ff0d22e9b4aaa345945b28cff4eb1f0cb5013ed1638a3caf3
---

# New error

```
Check file:///Users/xiaokeai/Desktop/concept_backend/src/concepts/TaskCatalog/TaskCatalog.test.ts
Uncaught error from ./src/concepts/TaskCatalog/TaskCatalog.test.ts FAILED

 ERRORS 

./src/concepts/TaskCatalog/TaskCatalog.test.ts (uncaught error)
error: (in promise) NotCapable: Requires read access to ".env", run again with the --allow-read flag
    return parse(Deno.readTextFileSync(filepath));
                      ^
    at Object.readTextFileSync (ext:deno_fs/30_fs.js:785:10)
    at parseFileSync (https://jsr.io/@std/dotenv/0.225.2/mod.ts:233:23)
    at loadSync (https://jsr.io/@std/dotenv/0.225.2/mod.ts:69:26)
    at https://jsr.io/@std/dotenv/0.225.2/load.ts:11:3
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./src/concepts/TaskCatalog/TaskCatalog.test.ts (uncaught error)

FAILED | 0 passed | 1 failed (0ms)

error: Test failed
```
